### ISSUE TITLE
fix jobsub_q -total command, which currently isn't working

### ISSUE THREAD

**Issue by goodenou** [fermitools/jobsub_lite#429]
Herb reported in INC000001152470 that `jobsub_q -totals` was not working for him. I confirmed that this is the case. Steve Timm brought up that the flag should really be `-total`, since condor_q removed the "s" from the flag a few years ago. I also tried `jobsub_q -total` and that did not work.

Shreyas confirms:
```
jobsub_q -G uboone -total
Attempting to get token from https://htvaultprod.fnal.gov:8200/ ... failed
Attempting kerberos auth with https://htvaultprod.fnal.gov:8200/ ... succeeded
Attempting to get token from https://htvaultprod.fnal.gov:8200/ ... succeeded
Storing vault token in /tmp/vt_u10610
Storing bearer token in /tmp/bt_token_uboone_Analysis_10610
JOBSUBJOBID                             OWNER           SUBMITTED     RUNTIME   ST PRIO   SIZE  COMMAND


[sbhat@fifeutilgpvm01 ~]$ condor_q -G uboone -total


-- Schedd: jobsub04.fnal.gov : <131.225.161.56:9615?... @ 06/01/23 09:17:41
Total for query: 11890 jobs; 1 completed, 0 removed, 5277 idle, 5643 running, 969 held, 0 suspended
Total for all users: 11890 jobs; 1 completed, 0 removed, 5277 idle, 5643 running, 969 held, 0 suspended



-- Schedd: jobsub05.fnal.gov : <131.225.161.135:9615?... @ 06/01/23 09:17:42
Total for query: 8144 jobs; 2 completed, 0 removed, 3182 idle, 4400 running, 560 held, 0 suspended
Total for all users: 8144 jobs; 2 completed, 0 removed, 3182 idle, 4400 running, 560 held, 0 suspended
...
```

**Comment by marcmengel** [comment]
I'm trying to decide what to do about jobsub_q --totals... If we just flag it as a formatting option, it's a Very Small Change and we get totals for query and totals for all separately for all the schedds, which sort-of meets the definition, but  I suspect is not what people want.  Otherwise we could catch it at the jobsub level, and after we run the regular condor_q  calls without -totals, we could run them again with -totals and collect the output and combine them, which could give us inconsistent results if jobs change status while we're running; or third we could make --totals run the condor_q's into a pipe and count the job statuses ourselves on the way past...

**Comment by shreyb** [comment]
So even though we had #433, I realize that one of the new unit tests requires a data file that was never checked in, `tests/data/jq_out.txt`.  Could you please push that to the repo, @marcmengel ?  I'm OK if you do a direct push to master.

**Comment by marcmengel** [comment]
File added directly on master.   Sorry for missing that...

**Comment by marcmengel** [comment]
Closing this out.
