### ISSUE TITLE
AlmaLinux 9 testing

### ISSUE THREAD

**Issue by shreyb** [fermitools/jobsub_lite#82]
We need to make sure that jobsub_lite works well with CentOS8.  Preferably, this should happen before our go-live.

**Comment by marcmengel** [comment]
Should we amend this to AlmaLinux 9?

**Comment by marcmengel** [comment]
So there should be an AlmaLinux9 image / images for Fermicloud mid-January or so, we should get one setup as a 
jobsub_lite node.

**Comment by shreyb** [comment]
> Should we amend this to AlmaLinux 9?

Absolutely.

**Comment by marcmengel** [comment]
So just to update this ticket; we have an Alma9 instance installed with jobsub_lite.
 
Unit tests say:
=========== 10 failed, 79 passed, 43 deselected, 15 errors in 24.00s ===========

Most failures are with voms_proxy_init; some others fail because a failed test is not cd-ing back to the test
directory. 

However, after updating the cilogon-silver.pem file in /etc/grid-security/certificates, the voms_proxy_init parts
are starting to work(?), and we're down to 2 test failing:

1. a failure in condor_submit_dag which looks like a condor bug, we get: "Error: Child was terminated by signal 11"
2. The other, test_get_creds_1, is complaining that the file pointed to by $X509_USER_PROXY doesn't exist(?)...

I'll post a note on fnal.slack.com#jobsub in slack about the test node so folks can get in and test.

**Comment by marcmengel** [comment]
So now other than the condor-submit-dag crash, the Alma9 tests appear to be working.

**Comment by shreyb** [comment]
Meeting on 2024-05-08:  `condor_submit_dag` works fine now (we think).  Will close, and reopen if that's not the case.
